Add missing <stdexcept>.
Resolves:

```console
FAILED: src/CMakeFiles/hareflow.dir/accumulator.cpp.o
/usr/bin/c++ -DHAREFLOW_BUILDING_STATIC -DHAREFLOW_EXPORTS -I/mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/include -isystem /mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -Wall -Werror -Wextra -MD -MT src/CMakeFiles/hareflow.dir/accumulator.cpp.o -MF src/CMakeFiles/hareflow.dir/accumulator.cpp.o.d -o src/CMakeFiles/hareflow.dir/accumulator.cpp.o -c /mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/src/accumulator.cpp
In file included from /mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/src/accumulator.cpp:1:
/mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/include/hareflow/detail/accumulator.h:36:1: error: expected class-name before ‘{’ token
   36 | {
      | ^
/mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/include/hareflow/detail/accumulator.h:37:16: error: ‘std::runtime_error’ has not been declared
   37 |     using std::runtime_error::runtime_error;
      |                ^~~~~~~~~~~~~
/mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/src/accumulator.cpp: In member function ‘bool hareflow::detail::Accumulator::add(uint64_t, hareflow::MessagePtr, hareflow::ConfirmationHandler)’:
/mnt/vcpkg-ci/b/hareflow/src/v0.1.1-d57a2b6dc8.clean/src/accumulator.cpp:39:72: error: too many initializers for ‘hareflow::detail::AccumulatorDestroyedException’
   39 |         throw AccumulatorDestroyedException{"Accumulator was destroyed"};
      |                                                                        ^
```

That BillyONeal guy back in https://github.com/coveooss/hareflow/commit/a9fe0c3732196c4e76095cec8a313e3c80382e6c can't do anything right